//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkSupportTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Users\\\\kobayauu\\\\OneDrive - Brother\\\\schedule.csv")]
        public string shcheduleFile {
            get {
                return ((string)(this["shcheduleFile"]));
            }
            set {
                this["shcheduleFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://133.151.236.52/TimePro-VG/page/OVg00050t.aspx?type=pclocking")]
        public string worktimeURL {
            get {
                return ((string)(this["worktimeURL"]));
            }
            set {
                this["worktimeURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int scheduleMode {
            get {
                return ((int)(this["scheduleMode"]));
            }
            set {
                this["scheduleMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int timerSpan {
            get {
                return ((int)(this["timerSpan"]));
            }
            set {
                this["timerSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10:00,12:00,12:15,12:30,12:45,15:00,18:00,20:00")]
        public string restTime {
            get {
                return ((string)(this["restTime"]));
            }
            set {
                this["restTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("朝会-00_現行機種[特殊印刷機] GG51100,アプリMTG-00_現行機種[特殊印刷機] GG51100,ソフトMTG-00_現行機種[特殊印刷機] GG5" +
            "1100,GTXpoly定例-03_GTXpoly GDGS300,GT CFT-00_現行機種[特殊印刷機] GG51100,GTXpoly製造定例（製造-開" +
            "発）-03_GTXpoly GDGS300,使い倒しWG(全体)-00_現行機種[特殊印刷機] GG51100,使い倒しWG【DTF】-00_現行機種[特殊印刷" +
            "機] GG51100")]
        public string regularMTG {
            get {
                return ((string)(this["regularMTG"]));
            }
            set {
                this["regularMTG"] = value;
            }
        }
    }
}
