//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// BGJServTool.rc で使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BGJSERVTOOL_DIALOG          102
#define IDS_SERV_SHEET_CAPTION          102
#define IDS_SERV_FIRST_CAUTION1         103
#define IDS_STRING103                   103
#define IDS_ADJ_THERMIS01_CHECK         103
#define IDS_ADJ_THERMIS01_01            104
#define IDS_ADJ_THERMIS02_01            105
#define IDS_ADJ_HVOLT01_01              106
#define IDS_ADJ_HVOLT02_01              107
#define IDS_ADJ_HVOLT03_01              108
#define IDS_ADJ_HVOLT04_01              109
#define IDS_HEAD_RANK1_1                110
#define IDS_ADJ_THERMIS01_DONE_CR       110
#define IDS_EEPROM_VIEW1_1              111
#define IDS_SEL_OTHER_OPE_1             112
#define IDS_CR_ORIGIN_1_1               112
#define IDS_QUERY_CANCEL                113
#define IDS_SERV_HEAD_RANK2_1           114
#define IDS_CHECK_CR_ORIGIN_DONE        114
#define IDS_ADJ_HVOLT05_01              115
#define IDS_ADJ_THERMIS03_01            116
#define IDS_ADJ_CR_SPEED1_1             117
#define IDS_ADJ_CR_SPEED2_1             118
#define IDS_TUBE_PUMP                   119
#define IDS_CHANGE_PUMP1_1              120
#define IDS_CHANGE_PUMP2_1              121
#define IDS_QUERY_CANCEL_AT_UPDATE      122
#define IDS_ERR_SETRANGE                122
#define IDS_FIRM_UPDATE4_1              123
#define IDS_SETIP_1                     123
#define IDS_READ_INFO1_1                124
#define IDS_READ_INFO2_1                125
#define IDS_SEL_OPE_1                   126
#define IDS_SERV_FIRST_1                127
#define IDR_MAINFRAME                   128
#define IDS_GET_DRV_LOG1_1              128
#define IDS_SETIP_2                     128
#define IDS_GET_DRV_LOG2_1              129
#define IDS_CHECK_SETIP_DONE            129
#define IDD_SERV_FIRST                  130
#define IDS_PROD_INFO1_1                130
#define IDS_BTN_HEAD                    130
#define IDD_SERV_REGULAR1               131
#define IDS_SET_DATE1_1                 131
#define IDD_SERV_GET_INFO               132
#define IDS_SET_LOG_SETTING1_1          132
#define IDS_TOTALPRINTS                 132
#define IDD_SERV_PARTS_CHG              133
#define IDS_SET_DATE2_1                 133
#define IDD_SERV_CHG_MAINB              134
#define IDS_SET_LOG_SETTING2_1          134
#define IDS_WHITEHEAD                   134
#define IDD_SERV_ADJ_THERMIS01          135
#define IDS_PROD_INFO2_1                135
#define IDS_COLORHEAD                   135
#define IDD_SERV_ADJ_THERMIS02          136
#define IDS_WCLEANER_CHG1_1             136
#define IDS_NO                          136
#define IDD_SERV_HEAD_VOLT01            137
#define IDS_WCLEANER_CHG2_1             137
#define IDS_HEADNO                      137
#define IDD_SERV_HEAD_VOLT02            138
#define IDS_WBLADE_CHG1_1               138
#define IDS_STARTDATE                   138
#define IDD_SERV_HEAD_VOLT03            139
#define IDS_WBLADE_CHG2_1               139
#define IDS_PRINTS                      139
#define IDD_SERV_HEAD_VOLT04            140
#define IDB_HEAD                        140
#define IDS_PRODUCT_INIT_END1_1         140
#define IDS_HEADCHECKER                 140
#define IDD_SERV_HEAD_RANK1             141
#define IDS_PRODUCT_END1_1              141
#define IDI_ICON_DIFF                   141
#define IDS_INSTALLDATE                 141
#define IDD_SERV_OTHER_OPE              142
#define IDS_CHANGE_BATTERY2_1           142
#define IDI_ICON_NONE                   142
#define IDD_SERV_EEPROM_VIEW1           143
#define IDS_CHANGE_BATTERY1_1           143
#define IDD_VIEW_EEP                    144
#define IDS_MAINB_CHG_TYPE1_1           144
#define IDD_SERV_HEAD_RANK2             145
#define IDS_REG_CHK_END1_1              145
#define IDD_SERV_HEAD_VOLT05            146
#define IDS_INIT_SET_END1_1             146
#define IDD_SERV_ADJ_THERMIS03          147
#define IDS_MAINB_CHG_EXEC1_1           147
#define IDD_SERV_ADJ_CR_SPEED1          148
#define IDS_LOG_CHECK1_1                148
#define IDD_SERV_ADJ_CR_SPEED2          149
#define IDS_LOG_CHECK2_1                149
#define IDD_SERV_FIRM_UPDATE1           150
#define IDS_HEAD_MOVE1_1                150
#define IDD_SERV_FIRM_UPDATE2           151
#define IDS_HEAD_MOVE2_1                151
#define IDD_SERV_FIRM_UPDATE3           152
#define IDS_FIRM_UPDATE4_2              152
#define IDD_SERV_FIRM_UPDATE4           153
#define IDS_SET_DATE2_2                 153
#define IDD_SERV_READ_INFO1             154
#define IDS_PRODUCT_INIT_END2_1         154
#define IDD_SERV_READ_INFO2             155
#define IDS_CHECK_SET1_1                155
#define IDD_SERV_SEL_OPE                156
#define IDS_FIRM_PUPDATE1_1             156
#define IDD_SERV_DRV_LOG1               157
#define IDS_FIRM_PUPDATE2_1             157
#define IDD_SERV_CR_ORIGIN              157
#define IDD_SERV_DRV_LOG2               158
#define IDS_FIRM_PUPDATE3_1             158
#define IDD_SERV_SET_PROD_INFO          159
#define IDS_FIRM_PUPDATE4_1             159
#define IDD_FIRE_ADJ_PAT                159
#define IDD_SERV_SET_DATE               160
#define IDS_FIRM_PUPDATE5_1             160
#define IDS_FIRM_PUPDATE6_1             161
#define IDB_SAMPLE_PATTERN              161
#define IDD_SERV_SET_LOG1               162
#define IDS_POFF_1_1                    162
#define IDR_ARP_FWDRVS_C                162
#define IDD_SERV_SET_DATE2              163
#define IDS_SET_PURGE_SETTING1_1        163
#define IDR_ARP_FWDRVS_M                163
#define IDD_SERV_SET_LOG2               164
#define IDS_SET_PURGE_SETTING2_1        164
#define IDR_ARP_FWDRVS_Y                164
#define IDD_SERV_SET_PROD_INFO2         165
#define IDS_SET_PURGE_SETTING0_1        165
#define IDR_ARP_FWDRVS_K                165
#define IDD_SERV_WCLEANER_CHG1          166
#define IDS_HEAD_ADJ_CAPTION            166
#define IDR_ARP_FWDRVS_ALL              166
#define IDD_SERV_WCLEANER_CHG2          167
#define IDS_FIRE_ADJ1_1                 167
#define IDD_SERV_WBLADE_CHG1            168
#define IDS_FIRE_ADJ2_1                 168
#define IDD_SERV_WBLADE_CHG2            169
#define IDS_FIRE_ADJ3_1                 169
#define IDD_SERV_PRODUCT_NEXT           170
#define IDS_FIRE_ADJ4_1                 170
#define IDD_SERV_PRODUCT_END            171
#define IDS_FIRE_ADJ5_1                 171
#define IDD_SERV_CHNAGE_BATTERY1        172
#define IDS_FIRE_ADJ6_1                 172
#define IDD_SERV_CHNAGE_BATTERY2        173
#define IDS_FIRE_ADJ7_1                 173
#define IDD_SERV_MAINB_CHG_SEL          174
#define IDS_FIRE_ADJ7_2                 174
#define IDD_SERV_REG_CHK_END            175
#define IDS_FIRE_ADJ8_1                 175
#define IDD_SERV_INIT_SET_END           176
#define IDS_FIRE_ADJ9_1                 176
#define IDD_SERV_MAINB_CHG_EXEC         177
#define IDS_FIRE_ADJ9_2                 177
#define IDD_SERV_LOG_CHECK1             178
#define IDS_FIRE_ADJ10_1                178
#define IDD_SERV_LOG_CHECK2             179
#define IDS_FIRE_ADJ4_1_J               179
#define IDS_ADJ_THERMIS01_02            179
#define IDD_SERV_PROD_SEL1              180
#define IDS_FIRE_ADJ4_1_E               180
#define IDS_ADJ_THERMIS02_02            180
#define IDD_SERV_HEAD_MOVE1             181
#define IDS_FIRE_ADJ5_1_J               181
#define IDS_ADJ_CR_SPEED1_2             181
#define IDD_SERV_HEAD_MOVE2             182
#define IDS_FIRE_ADJ5_1_E               182
#define IDS_ADJ_CR_SPEED2_2             182
#define IDD_PROD_FIRM_UPDATE1           183
#define IDS_FIRE_ADJ6_1_J               183
#define IDS_PROD_INFO1_2                183
#define IDD_PROD_FIRM_UPDATE2           184
#define IDS_FIRE_ADJ6_1_E               184
#define IDD_PROD_FIRM_UPDATE3           185
#define IDS_FIRE_ADJ7_1_J               185
#define IDD_PROD_FIRM_UPDATE4           186
#define IDS_FIRE_ADJ7_1_E               186
#define IDD_PROD_FIRM_UPDATE6           187
#define IDS_FIRE_ADJ7_2_J               187
#define IDD_PROD_FIRM_UPDATE5           188
#define IDS_FIRE_ADJ7_2_E               188
#define IDD_SERV_POFF                   189
#define IDS_FIRE_ADJ8_1_J               189
#define IDD_SERV_CHK_RANK1              190
#define IDS_FIRE_ADJ8_1_E               190
#define IDD_SERV_PRODUCT_NEXT1          191
#define IDS_FIRE_ADJ9_1_J               191
#define IDD_SERV_SET_PROD_INFO1         192
#define IDS_FIRE_ADJ9_1_E               192
#define IDD_SERV_SET_PURGE1             193
#define IDS_FIRE_ADJ9_2_J               193
#define IDD_SERV_SET_PURGE2             194
#define IDS_FIRE_ADJ9_2_E               194
#define IDD_SERV_SET_PURGE0             195
#define IDS_CR_CHANGE1_1                195
#define IDD_FIRE_ADJ1                   196
#define IDS_SAMPLE1_1                   196
#define IDD_FIRE_ADJ2                   197
#define IDS_SERV_FIRE_ADJ1_1            197
#define IDD_FIRE_ADJ3                   198
#define IDS_SERV_FIRE_ADJ2_1            198
#define IDD_FIRE_ADJ4                   199
#define IDS_SERV_FIRE_ADJ3_1            199
#define IDD_FIRE_ADJ5                   200
#define IDS_SERV_FIRE_ADJ4_1            200
#define IDD_FIRE_ADJ6                   201
#define IDS_RADIO_FIRE_ADJ              201
#define IDD_FIRE_ADJ7                   202
#define IDS_RADIO_LOG_CHK               202
#define IDD_FIRE_ADJ8                   203
#define IDS_SERV_PSEL1_1                203
#define IDD_FIRE_ADJ9                   204
#define IDS_COPYRIGHTS                  204
#define IDD_FIRE_ADJ10                  205
#define IDS_VIEW_LOG1_1                 205
#define IDD_SERV_CR_CHANGE              206
#define IDS_LOG_ANAL1_1                 206
#define IDD_PROD_FIRST                  207
#define IDS_ADJ_HVOLT00_01              207
#define IDR_MENU_PROD                   208
#define IDD_PROD_PRN_SEL                208
#define IDS_ADJ_HVOLT05_02              208
#define IDD_PROD_INFO1                  209
#define IDS_RADIO_PARTS_CHANGE          209
#define IDD_DLG_PROD_INIT1              210
#define IDS_RADIO_VIEW_LOG              210
#define IDD_DLG_PROD_INIT2              211
#define IDS_LOG_PROG1_1                 211
#define IDD_SERV_SET_LR1                211
#define IDD_DLG_PROD_INIT3              212
#define IDS_LOGTXT_PROG1_1              212
#define IDR_TEMPL_8001                  213
#define IDD_SERV_FIRE_ADJ1              213
#define IDS_UPD_FIRST_1                 213
#define IDR_TEMPL_8001_14               213
#define IDR_TEMPL_8002                  214
#define IDD_SERV_FIRE_ADJ2              214
#define IDS_UPD_FIRST_2                 214
#define IDR_TEMPL_8002_13               214
#define IDR_TEMPL_8003                  215
#define IDD_SERV_FIRE_ADJ3              215
#define IDS_UPD_PSEL_1                  215
#define IDR_TEMPL_8003_21               215
#define IDR_TEMPL_8004                  216
#define IDD_SERV_FIRE_ADJ4              216
#define IDS_UPD_FIRM_STEP_1             216
#define IDR_TEMPL_8004_15               216
#define IDR_TEMPL_8005                  217
#define IDD_SERV_PSEL                   217
#define IDS_UPD_FIRM_STEP_2             217
#define IDR_TEMPL_8005_25               217
#define IDR_TEMPL_8006                  218
#define IDS_UPD_FIRM_STEP_3             218
#define IDR_TEMPL_8006_14               218
#define IDR_TEMPL_8010                  219
#define IDS_UPD_FIRM_STEP_4             219
#define IDR_TEMPL_8010_2005_0623        219
#define IDR_TEMPL_8011                  220
#define IDS_UPD_FIRM_STEP_5             220
#define IDR_TEMPL_8011_2005_0613        220
#define IDR_TEMPL_8012                  221
#define IDS_UPD_FIRM_STEP_6             221
#define IDR_TEMPL_8012_2005_0228        221
#define IDR_TEMPL_8013                  222
#define IDS_UPD_FIRM_STEP_7             222
#define IDR_TEMPL_8013_2003_0807        222
#define IDB_BITMAP_BLACK                223
#define IDS_UPD_FIRM_ERR1               223
#define IDB_BITMAP_MAGENTA              224
#define IDD_DLG_LOG_PROGRESS            224
#define IDS_NO_UPDATE                   224
#define IDB_BITMAP_CYAN                 225
#define IDD_SERV_VIEW_LOG               225
#define IDS_CANNOT_UPDATE               225
#define IDB_BITMAP_YELLOW               226
#define IDD_EEPROM_SEL_DISP             226
#define IDS_RADIO_SET_DATE              226
#define IDD_LOG_VIEW                    227
#define IDS_ZONE_TITLE                  227
#define IDD_DLG_LOG_INFO                228
#define IDS_PROD_FIRST1_1               228
#define IDD_DLG_LOGTXT_PROGRESS         229
#define IDB_SAMPLE_PATTERN2             229
#define IDS_PROD_FIRST1_2               229
#define IDD_PROP_LOG_INFO               230
#define IDR_FIRM_FONT                   230
#define IDS_PROD_PSEL_1                 230
#define IDD_LOG_ANALYZE                 231
#define IDR_FIRM_SH                     231
#define IDS_FIRM_PUPDATE_ERR1           231
#define IDD_SERV_HEAD_VOLT00            232
#define IDR_FIRM_BY                     232
#define IDS_LOGCSV_PROG1_1              232
#define IDR_FIRM_BYBOOT                 233
#define IDD_UPD_FIRST                   233
#define IDS_EER_FILE_OPEN               233
#define IDD_UPD_FIRM1                   234
#define IDS_ERR_INPUT_FILENAME          234
#define IDR_FIRM_STRING                 235
#define IDD_UPD_FIRM2                   235
#define IDS_ERR_DROP                    235
#define IDR_FIRM_MAINTE                 236
#define IDD_UPD_FIRM3                   236
#define IDS_ERR_MEM_ENTRY               236
#define IDR_FIRM_ARP_NOZZLE             237
#define IDD_UPD_FIRM4                   237
#define IDS_EER_COMMUNICATION           237
#define IDR_FIRM_ARP_STANDARD           238
#define IDD_UPD_FIRM5                   238
#define IDS_EER_FILE_IO                 238
#define IDD_UPD_FIRM6                   239
#define IDS_REPLACE                     239
#define IDD_UPD_FIRM7                   240
#define IDS_ERR_LOGFILE                 240
#define IDD_DLG_TOOL_SEL                241
#define IDS_ERR_MEMORY                  241
#define IDD_DLG_LOGCSV_PROGRESS         242
#define IDS_ERR_BUG                     242
#define IDD_SERV_VIEW_STAT              243
#define IDS_INPUT_PATTERN               243
#define IDS_OFFLINE                     244
#define IDS_ERR_ACCESS_DENIED           245
#define IDS_SERV_FIRE_ADJ1_1_5          246
#define IDD_SERV_FIRE_ADJ1_5            247
#define IDS_FIRE_ADJ6_M                 247
#define IDS_C                           248
#define IDS_M                           249
#define IDS_Y                           250
#define IDD_FIRE_ADJ_PAT2               250
#define IDS_K                           251
#define IDS_ERR_OUTOFRANGE              252
#define IDB_SAMPLE_PATTERN3             252
#define IDS_ERR_OUTOFRANGE2             253
#define IDS_TITLE_1                     254
#define IDS_TITLE_2                     255
#define IDS_TITLE_3                     256
#define IDS_TITLE_4                     257
#define IDD_FIRE1                       257
#define IDS_TITLE_5                     258
#define IDS_TITLE_6                     259
#define IDS_TITLE_7                     260
#define IDS_TITLE_8                     261
#define IDS_TITLE_9                     262
#define IDS_TITLE_10                    263
#define IDD_IN_ADVANCE_MAIN             263
#define IDS_TITLE_11                    264
#define IDS_TITLE_12                    265
#define IDD_SET_POS                     265
#define IDS_TITLE_13                    266
#define IDS_TITLE_14                    267
#define IDS_TITLE_15                    268
#define IDS_TITLE_16                    269
#define IDS_TITLE_17                    270
#define IDS_TITLE_18                    271
#define IDS_TITLE_19                    272
#define IDS_TITLE_20                    273
#define IDS_TITLE_21                    274
#define IDS_TITLE_22                    275
#define IDS_TITLE_23                    276
#define IDS_TITLE_24                    277
#define IDS_TITLE_25                    278
#define IDD_SERV_SET_LR2                278
#define IDS_TITLE_26                    279
#define IDD_RESET_VOLTAGE               279
#define IDS_TITLE_27                    280
#define IDS_TITLE_28                    281
#define IDD_SERV_RESET_TUBE1            281
#define IDS_TITLE_LOGFILEINFO           282
#define IDD_SERV_RESET_TUBE2            282
#define IDS_TITLE_LOGPROG               283
#define IDD_SERV_CHNAGE_PUMP1           283
#define IDS_TITLE_LOGCSVPROG            284
#define IDD_SERV_CHNAGE_PUMP2           284
#define IDD_SERV_CHNAGE_PUMP1_          284
#define IDR_TEMPL_8014                  284
#define IDS_TITLE_LOGTXTPROG            285
#define IDR_TEMPL_8015                  285
#define IDS_TITLE_EEPDISPSEL            286
#define IDD_SET_IP                      286
#define IDS_TITLE_LOGANAL               287
#define IDR_TEMPLATE1                   287
#define IDR_TEMPL_8016                  287
#define IDS_TITLE_LOGVIEW               288
#define IDR_TEMPL_8017                  288
#define IDS_TITLE_STAT                  289
#define IDS_CLOSE                       290
#define IDD_MAIN_BOARD_BRANCH           290
#define IDS_HOWTO                       291
#define IDD_EEPROM_RESTORE1             291
#define IDS_FIRE_EXAMPLE                292
#define IDS_SERV_FIRE_ADJ4_2            293
#define IDD_BACKUP                      293
#define IDS_SERV_FIRE_ADJ4_3            294
#define IDD_RTC_SET_AND_RESET_EEPROM    294
#define IDS_FIRE_RESTART                295
#define IDD_IP_CLEAR                    295
#define IDD_BARCODE                     296
#define IDS_FIRE_CASE2                  297
#define IDS_LOGFILE_INFO_1              298
#define IDD_INIT_INK_STATE              298
#define IDS_EEPROM_VIEW1_2              299
#define IDS_DISPLAY                     300
#define IDD_VRATING                     300
#define IDS_CHK_COMPARE                 301
#define IDD_WHITE_HALT2                 301
#define IDS_LOG_ANAL1_2                 302
#define IDD_PLANTEN_FEEDING             302
#define IDS_LOG_ANAL1_3                 303
#define IDD_RTC_AND_BATTERY             303
#define IDS_LOG_CHECK2_2                304
#define IDD_BACKUP2                     304
#define IDS_CONVERT_TO_TEXT             305
#define IDD_VIEW_HEAD                   305
#define IDS_VOLT                        306
#define IDD_BARCODE_RE                  306
#define IDD_BARCODE_REGION              306
#define IDS_TIME_LEFT                   307
#define IDS_BROWSE                      308
#define IDD_VIEW_HEADCHECK              308
#define IDS_LOGFILE                     309
#define IDR_TEMPL_8018                  309
#define IDS_SELECTMENU                  310
#define IDR_TEMPL_8019                  310
#define IDS_HEADS                       311
#define IDR_TEMPL_8020                  311
#define IDS_CR_ADJ                      312
#define IDR_TEMPL_8021                  312
#define IDS_BATTERY                     313
#define IDR_TEMPL_8022                  313
#define IDS_CR_BOARD                    314
#define IDS_MAIN_BOARD                  315
#define IDS_POWER_BOARD                 316
#define IDS_RADIO_CR_MOTOR              317
#define IDS_SELECT_PRINTER              318
#define IDS_RESCAN                      319
#define IDS_READ_INFO1_2                320
#define IDS_READ_INFO1_3                321
#define IDS_READ_INFO1_4                322
#define IDS_READ_INFO2_2                323
#define IDS_SELECT_OPE                  324
#define IDS_SET_DATE1_2                 325
#define IDS_MONTH                       326
#define IDS_DAY                         327
#define IDS_YEAR                        328
#define IDS_HOUR                        329
#define IDS_MINUTE                      330
#define IDS_SECOND                      331
#define IDS_USE_PC                      332
#define IDS_BTN_INFO                    333
#define IDS_BTN_LOG                     334
#define IDS_BTN_SETTINGS                335
#define IDS_BTN_LOG_ANAL                336
#define IDS_BTN_STAT                    337
#define IDS_LOGFILE1                    338
#define IDS_CHECK_DATE                  339
#define IDS_CHECK_MACHINE               340
#define IDS_CHECK_SEPARATE              341
#define IDS_FOLDER                      342
#define IDS_DAY1                        343
#define IDS_JOB                         344
#define IDS_PL_DOT                      345
#define IDS_SAVE                        346
#define IDS_CANCEL                      347
#define IDS_TITLE_EEP_DISP              348
#define IDS_BLOCKID                     349
#define IDS_VERSION                     350
#define IDC_SAVEAS                      351
#define IDS_TEMPERATURE                 352
#define IDS_FAHRENHEIGHT                353
#define IDS_CELSIUS                     354
#define IDS_LEFT_OR_RIGHT_1             356
#define IDS_LEFT                        357
#define IDS_RIGHT                       358
#define IDS_BOTH                        359
#define IDS_FIRE_1_1_LEFT               360
#define IDS_FIRE_1_1_RIGHT              361
#define IDS_FIRE_1_1_BOTH               362
#define IDS_FIRE_1_2                    363
#define IDS_BTN_OPEN_GTMAINTE           364
#define IDS_CHECK_FIRE_DONE             365
#define IDS_IN_ADVANCE_MAIN_1_1         370
#define IDS_SET_MAIN_SETTING_1          371
#define IDS_FIRE_1_3                    373
#define IDS_SETPOS_1                    375
#define IDS_SETPOS_2                    376
#define IDS_SETPOS_3                    378
#define IDS_CHECK_SETPOS_DONE           380
#define IDS_SEL_OPE_2                   381
#define IDS_FILE_EXIST                  382
#define IDS_RADIO_SET_LR                383
#define IDS_SET_LR1_1                   384
#define IDS_CLICK_NEXT                  385
#define IDS_SET_LR2_1                   386
#define IDS_SERV_FIRST_2                387
#define IDS_RESET_VOLRAGE_1             388
#define IDS_DR                          389
#define IDS_RADIO_RESET_TUBE_WORNING    390
#define IDS_RESET_TUBE_1                391
#define IDS_RESET_TUBE_2_1              392
#define IDS_LCD_BOARD                   393
#define IDS_MAIN_BOARD_BRANCH1_1        398
#define IDS_MAIN_BOARD_BRANCH1_2        399
#define IDS_MAIN_BOARD_BRANCH1_3        400
#define IDS_EEPROM_RESTORE1_1           401
#define IDS_EEPROM_RESTORE2_1           403
#define IDS_EERPOM_BACKUP               404
#define IDS_RTC_AND_RESET1              405
#define IDS_IP_CLEAR1                   406
#define IDS_BARCODE1                    407
#define IDS_BARCODE2                    408
#define IDS_BARCODE3                    409
#define IDS_WHITE_HALT1                 410
#define IDS_WHITE_HALT2                 411
#define IDS_INIT_INK_STATE1             412
#define IDS_INIT_INK_STATE2             413
#define IDS_INIT_INK_STATE3             414
#define IDS_INIT_INK_STATE4             415
#define IDS_INIT_INK_STATE5             416
#define IDS_VRATING1                    417
#define IDS_VRATING2                    418
#define IDS_VRATING3                    419
#define IDS_VRATING4                    420
#define IDS_INIT_INK_STATE6             421
#define IDS_INIT_INK_STATE7             422
#define IDS_INIT_INK_STATE8             423
#define IDS_ERR_EIGHTEEN_CODE           503
#define IDS_ERR_SERIAL_CODE             504
#define IDS_WHITE_HALT3                 505
#define IDS_WHITE_HALT4                 506
#define IDS_RTC_AND_BATTERY1            507
#define IDS_PLATEN_FEEDING1             508
#define IDS_PLATEN_FEEDING2             509
#define IDS_PLATEN_FEEDING3             510
#define IDS_PLATEN_FEEDING4             511
#define IDS_EEPROM_BACKUP1_2            512
#define IDS_EXAM1                       513
#define IDS_EXAM2                       514
#define IDS_RADIO_REGION_JPN            515
#define IDS_RADIO_REGION_US             516
#define IDS_RADIO_REGION_EUR            517
#define IDS_RADIO_REGION_AUS            518
#define IDS_RADIO_REGION_CHN            519
#define IDS_OPERATIONS                  520
#define IDS_HUMID_FAN                   521
#define IDD_HUMIDFAN                    522
#define IDS_HUMIDFAN_MSG1               523
#define IDD_UPG_PSEL                    524
#define IDD_UPDATE_FIRM                 525
#define IDD_WAIT_ACTION                 526
#define IDD_SET_18CODE                  527
#define IDC_CBX_PRINTER                 1000
#define IDC_RADIO_INITIAL               1001
#define IDC_RADIO_FIRE_ADJ              1001
#define IDC_RADIO_REGULAR               1002
#define IDC_EDIT_STATUS                 1002
#define IDC_RADIO_PARTS_CHANGE          1003
#define IDC_PROGRESS_GET_INFO           1003
#define IDC_RADIO_HEAD                  1004
#define IDC_RADIO_UPGRADE               1004
#define IDC_RADIO_WIPE                  1005
#define IDC_CHK_SKIP                    1005
#define IDC_RADIO_OTHER                 1005
#define IDC_RADIO_MAINTE_UNIT           1006
#define IDC_SERV_FIRST_CAUTION1         1006
#define IDC_SERV_FIRST_1                1006
#define IDC_RADIO_CR_BOARD              1007
#define IDC_ADJ_THERMIS01_01            1007
#define IDC_RADIO_MAIN_BOARD            1008
#define IDC_IMAGE1                      1008
#define IDC_RADIO_BATTERY               1009
#define IDC_ADJ_THERMIS02_01            1009
#define IDC_RADIO_CR_MOTOR              1010
#define IDC_RADIO_FAHRENHEIGHT          1010
#define IDC_RADIO_CR_ADJ                1010
#define IDC_RADIO_CELSIUS               1011
#define IDC_RADIO_POWER_BOARD           1011
#define IDC_RADIO_CR_MOTOR2             1012
#define IDC_EDIT_FTEMP                  1013
#define IDC_RADIO_CR_MOTOR3             1013
#define IDC_RADIO_PUMP                  1013
#define IDC_EDIT_CTEMP                  1014
#define IDC_ADJ_HVOLT01_01              1014
#define IDC_ADJ_HVOLT02_01              1015
#define IDC_EDIT_CH0_VOLT               1016
#define IDC_EDIT_CH1_VOLT               1017
#define IDC_ADJ_HVOLT03_01              1017
#define IDC_EDIT_CH2_VOLT               1018
#define IDC_EDIT_CH3_VOLT               1019
#define IDC_ADJ_HVOLT04_01              1020
#define IDC_HEAD_RANK1_1                1021
#define IDC_CHK_K                       1022
#define IDC_RANK_K                      1023
#define IDC_NUMBER_K                    1024
#define IDC_RADIO_EEPROM_CHK            1024
#define IDC_RADIO_VIEW_LOG              1024
#define IDC_CHK_M                       1025
#define IDC_RADIO_ELSE1                 1025
#define IDC_RADIO_LOG_CHK               1025
#define IDC_RADIO_LOG                   1025
#define IDC_RANK_M                      1026
#define IDC_EEPROM_VIEW1_1              1026
#define IDC_RADIO_SET_DATE              1026
#define IDC_NUMBER_M                    1027
#define IDC_CBX_EEP_TYPE                1027
#define IDC_RADIO_SET_LR                1027
#define IDC_CHK_C                       1028
#define IDC_RADIO_RESET_TUBE_WORNING    1028
#define IDC_RANK_C                      1029
#define IDC_BTN_VIEW                    1029
#define IDC_NUMBER_C                    1030
#define IDC_COMMENT                     1030
#define IDC_CHK_Y                       1031
#define IDC_BLOCK_ID                    1031
#define IDC_RANK_Y                      1032
#define IDC_VIRSION                     1032
#define IDC_NUMBER_Y                    1033
#define IDC_STR_VERSION                 1033
#define IDC_SIDE                        1034
#define IDC_LIST                        1036
#define IDC_LIST2                       1037
#define IDC_SEL_OTHER_OPE_1             1038
#define IDC_SERV_HEAD_RANK2_1           1040
#define IDC_ADJ_HVOLT05_01              1041
#define IDC_ADJ_THERMIS03_01            1042
#define IDC_ADJ_CR_SPEED1_1             1043
#define IDC_ADJ_CR_SPEED2_1             1044
#define IDC_FIRM_UPDATE1_1              1045
#define IDC_FIRM_UPDATE2_1              1046
#define IDC_EDIT_SH                     1047
#define IDC_BROWSE_SH                   1048
#define IDC_EDIT_BY                     1049
#define IDC_FIRM_UPDATE3_1              1049
#define IDC_BROWSE_BY                   1050
#define IDC_FIRM_UPDATE4_1              1050
#define IDC_READ_INFO1_1                1051
#define IDC_READ_BYTE                   1052
#define IDC_READ_INFO2_1                1054
#define IDC_SAVED_DIR                   1055
#define IDC_SEL_OPE_1                   1056
#define IDC_GET_DRV_LOG1_1              1057
#define IDC_SEL_OPE_2                   1057
#define IDC_BTN_CLOSE                   1058
#define IDC_GET_DRV_LOG2_1              1059
#define IDC_MODEL_ID                    1060
#define IDC_MODEL_VER                   1061
#define IDC_LOT_NUMBER                  1062
#define IDC_PRODUCT_NUMBER              1063
#define IDC_PROD_INFO1_1                1064
#define IDC_MANUFACTURER_NO             1065
#define IDC_SET_DATE1_1                 1066
#define IDC_SET_LOG_SETTING1_1          1069
#define IDC_SET_DATE2_1                 1070
#define IDC_SET_LOG_SETTING2_1          1071
#define IDC_PROD_INFO2_1                1072
#define IDC_USE_PC                      1073
#define IDC_YEAR                        1074
#define IDC_MONTH                       1075
#define IDC_WCLEANER_CHG1_1             1075
#define IDC_DAY                         1076
#define IDC_WCLEANER_CHG2_1             1076
#define IDC_HOUR                        1077
#define IDC_WBLADE_CHG1_1               1077
#define IDC_MINUTE                      1078
#define IDC_WBLADE_CHG2_1               1078
#define IDC_SECOND                      1079
#define IDC_RADIO_PRODUCT_START         1079
#define IDC_RADIO_ELSE                  1079
#define IDC_RADIO_CHK_RANK              1079
#define IDC_RADIO_PRODUCT_FINISH        1080
#define IDC_RADIO_PRODUCT               1080
#define IDC_RADIO_EEP_COMPARE           1080
#define IDC_PRODUCT_INIT_END1_1         1081
#define IDC_RADIO_PURGE_SET             1081
#define IDC_PRODUCT_END1_1              1082
#define IDC_CHANGE_BATTERY1_1           1083
#define IDC_CHANGE_BATTERY2_1           1084
#define IDC_MAINB_CHG_TYPE1_1           1085
#define IDC_RADIO_READABLE_EEP          1086
#define IDC_RADIO_CANT_READ_EEP         1087
#define IDC_REG_CHK_END1_1              1088
#define IDC_INIT_SET_END1_1             1090
#define IDC_LOG_LEVEL                   1091
#define IDC_LOG_TYPE                    1092
#define IDC_MAINB_CHG_EXEC1_1           1092
#define IDC_LOG_SAVE                    1093
#define IDC_VERSION                     1093
#define IDC_COPYRIGHT                   1094
#define IDC_LOG_CHECK1_1                1094
#define IDC_LOGFILE_NAME                1095
#define IDC_BROWSE                      1096
#define IDC_LOG_VERSION                 1097
#define IDC_LOG_CHECK2_1                1099
#define IDC_CHK_OPE                     1100
#define IDC_CHK_WRN                     1100
#define IDC_CHK_STS                     1101
#define IDC_CHK_ERR                     1102
#define IDC_CHK_MNT                     1103
#define IDC_CHK_INF                     1104
#define IDC_BTN_DISP                    1105
#define IDC_PROD_SEL1_1                 1106
#define IDC_BTN_CSV                     1106
#define IDC_RADIO_PROD_START            1107
#define IDC_RADIO_PROD_END              1108
#define IDC_HEAD_MOVE1_1                1109
#define IDC_RADIO_SERVICE               1109
#define IDC_HEAD_POS                    1110
#define IDC_RADIO_PROD_BEFORE_HEAD      1110
#define IDC_HEAD_MOVE2_1                1111
#define IDC_RADIO_PROD_CHK              1111
#define IDC_RADIO_HEAD_MOVE             1112
#define IDC_TIME_LEFT                   1113
#define IDC_POFF_1_1                    1114
#define IDC_CHECK_SET1_1                1115
#define IDC_PRODUCT_INIT_END2_1         1118
#define IDC_FIRM_PUPDATE1_1             1119
#define IDC_FIRM_PUPDATE2_1             1120
#define IDC_FIRM_PUPDATE3_1             1121
#define IDC_FIRM_PUPDATE4_1             1122
#define IDC_FIRM_PUPDATE5_1             1123
#define IDC_FIRM_PUPDATE6_1             1124
#define IDC_CUSTOM1                     1125
#define IDC_SET_PURGE_SETTING1_1        1126
#define IDC_PRINT_COUNT                 1127
#define IDC_INTERVAL_MINUTES            1128
#define IDC_SET_PURGE_SETTING2_1        1129
#define IDC_SET_PURGE_SETTING0_1        1131
#define IDC_FIRE_ADJ1_1                 1132
#define IDC_FIRE_ADJ2_1                 1133
#define IDC_FIRE_ADJ3_1                 1134
#define IDC_RADIO_K                     1135
#define IDC_RADIO_M                     1136
#define IDC_RADIO_C                     1137
#define IDC_RADIO_Y                     1138
#define IDC_FIRE_ADJ4_1                 1139
#define IDC_EDIT_COLOR                  1140
#define IDC_EDIT_PRINTER                1141
#define IDC_EDIT_PAT_NUM                1143
#define IDC_FIRE_ADJ8_1                 1144
#define IDC_EDIT_PAT_NUM_K              1144
#define IDC_FIRE_ADJ5_1                 1145
#define IDC_EDIT_PAT_NUM_M              1145
#define IDC_FIRE_ADJ7_1                 1146
#define IDC_EDIT_PAT_NUM_C              1146
#define IDC_FIRE_ADJ9_1                 1147
#define IDC_FIRE_ADJ7_2                 1147
#define IDC_EDIT_PAT_NUM_Y              1147
#define IDC_FIRE_ADJ9_2                 1148
#define IDC_EDIT_PAT_NUM_C2             1148
#define IDC_FIRE_ADJ10_1                1149
#define IDC_EDIT_PAT_NUM_Y2             1149
#define IDC_RD_OK                       1150
#define IDC_RD_NG                       1151
#define IDC_VER                         1151
#define IDC_FIRE_ADJ6_1                 1152
#define IDC_FIRE_ADJ6_M                 1153
#define IDC_SAMPLE1_1                   1154
#define IDC_BTN_PAT_SAMPLE              1155
#define IDC_ST_K                        1156
#define IDC_ST_M                        1157
#define IDC_ST_C                        1158
#define IDC_ST_Y                        1159
#define IDC_NUM_TITLE                   1160
#define IDC_CR_CHANGE1_1                1161
#define IDC_PROD_FIRST1_1               1162
#define IDC_TIME                        1164
#define IDC_SERIAL                      1165
#define IDC_LOT                         1166
#define IDC_BTN_INITIAL                 1166
#define IDC_EDIT_LOT                    1167
#define IDC_BTN_INIT_SEQ_NO             1168
#define IDC_EDIT_PC                     1169
#define IDC_PROGRESS_UPLOAD             1170
#define IDC_SERV_FIRE_ADJ1_1            1171
#define IDC_SERV_FIRE_ADJ2_1            1172
#define IDC_SERV_FIRE_ADJ3_1            1173
#define IDC_SERV_FIRE_ADJ4_1            1174
#define IDC_SERV_PSEL1_1                1176
#define IDC_BTN_RESCAN                  1177
#define IDC_LOG_FILE_NAME               1179
#define IDC_BTN_BROWSE                  1180
#define IDC_LOG_PROG1_1                 1181
#define IDC_PROGRESS1                   1182
#define IDC_CUSTOMER                    1183
#define IDC_VIEW_LOG1_1                 1187
#define IDC_BTN_SETTINGS                1188
#define IDC_BTN_LOG                     1189
#define IDC_LOG_FILE                    1190
#define IDC_BTN_INFO                    1191
#define IDC_BTN_STAT                    1192
#define IDC_BTN_INFO2                   1193
#define IDC_BTN_HEAD                    1193
#define IDC_BTN_SAVEAS                  1195
#define IDC_CHK_COMPARE                 1196
#define IDC_FILE_NAME                   1198
#define IDC_EDIT_INFO                   1201
#define IDC_LOGTXT_PROG1_1              1202
#define IDC_BTN_HELP                    1204
#define IDC_CBX_SELECT                  1205
#define IDC_LOG_ANAL1_1                 1206
#define IDC_BTN_BACK                    1206
#define IDC_INFO                        1207
#define IDC_BTN_LOG_ANAL                1208
#define IDC_CBX_LIMIT                   1210
#define IDC_ADJ_HVOLT00_01              1211
#define IDC_UPD_FIRST_1                 1212
#define IDC_UPD_FIRST_2                 1213
#define IDC_COPYRIGHTS                  1215
#define IDC_UPD_FIRM_1                  1217
#define IDC_UPD_FIRM_STEP               1220
#define IDC_RADIO_FIRING_ADJUST         1221
#define IDC_RADIO_SERVICE_TOOL          1222
#define IDC_RADIO_PRODUCTION            1223
#define IDC_RADIO_UPDATE                1224
#define IDC_CHECK_DEMO                  1225
#define IDC_DATE_TYPE                   1226
#define IDC_TIMEZONE                    1227
#define IDC_ZONE_TITLE                  1228
#define IDC_PROD_PSEL_1                 1229
#define IDC_TITLE_SERIAL                1230
#define IDC_TITLE_LOT                   1231
#define IDC_EDIT_FIRMVER                1232
#define IDC_LOGCSV_PROG1_1              1233
#define IDC_EDIT_YEAR1                  1234
#define IDC_EDIT_MONTH1                 1235
#define IDC_EDIT_FOLDER                 1236
#define IDC_EDIT_DAY1                   1237
#define IDC_EDIT_YEAR2                  1238
#define IDC_EDIT_MONTH2                 1239
#define IDC_EDIT_DAY2                   1240
#define IDC_EDIT_STATDAY                1241
#define IDC_EDIT_STATJOB                1242
#define IDC_BUTTON_FOLDER               1243
#define IDC_BUTTON_SAVE                 1244
#define IDC_BUTTON_CANCEL               1245
#define IDC_EDIT_PLDOT                  1246
#define IDC_EDIT_MACHINE                1248
#define IDC_SPIN_YEAR1                  1251
#define IDC_SPIN_MONTH1                 1252
#define IDC_SPIN_DAY1                   1253
#define IDC_SPIN_YEAR2                  1254
#define IDC_SPIN_MONTH2                 1255
#define IDC_SPIN_DAY2                   1256
#define IDC_CHECK_DATE                  1257
#define IDC_CHECK_MACHINE               1258
#define IDC_SPIN_PLDOT                  1259
#define IDC_SERV_FIRE_ADJ1_1_5          1259
#define IDC_COMBO_K                     1260
#define IDC_COMBO_M                     1261
#define IDC_COMBO_C                     1262
#define IDC_COMBO_Y                     1263
#define IDC_SERV_FIRE_ADJ4_2            1263
#define IDC_SERV_FIRE_ADJ4_3            1264
#define IDC_STATIC_1                    1265
#define IDC_LOGFILE_INFO_1              1266
#define IDC_EEPROM_VIEW1_2              1267
#define IDC_LOG_ANAL1_2                 1268
#define IDC_LOG_ANAL1_3                 1269
#define IDC_TIME_LEFT1                  1270
#define IDC_VOLT                        1271
#define IDC_SELECTMENU                  1272
#define IDC_SELECT_PRINTER              1273
#define IDC_READ_INFO1_2                1274
#define IDC_READ_INFO1_3                1275
#define IDC_READ_INFO1_4                1276
#define IDC_READ_INFO2_2                1277
#define IDC_SELECT_OPE                  1278
#define IDC_SET_DATE1_2                 1279
#define IDC_MONTH1                      1280
#define IDC_DAY1                        1281
#define IDC_YEAR1                       1282
#define IDC_HOUR1                       1283
#define IDC_MINUTE1                     1284
#define IDC_SECOND1                     1285
#define IDC_FOLDER                      1286
#define IDC_JOB                         1287
#define IDC_PL_DOT                      1288
#define IDC_BLOCKID                     1289
#define IDC_TEMPERATURE                 1290
#define IDC_WHITE                       1290
#define IDC_RADIO_LEFT                  1291
#define IDC_COLOR                       1291
#define IDC_RADIO_RIGHT                 1292
#define IDC_FIRE_1_1                    1295
#define IDC_FIRE_1_2                    1296
#define IDC_BTN_OPEN_GTMAINTE           1297
#define IDC_CHECK_FIRE_DONE             1298
#define IDC_FIRE_1_3                    1299
#define IDC_IN_ADVANCE_MAIN_1_1         1304
#define IDC_SETPOS_1                    1309
#define IDC_SETPOS_2                    1310
#define IDC_SETPOS_3                    1311
#define IDC_CHECK_SETPOS_DONE           1312
#define IDC_RADIO2                      1315
#define IDC_RADIOLEFT                   1316
#define IDC_SET_LR1_1                   1316
#define IDC_SET_LR1_2                   1317
#define IDC_SET_LR2_1                   1318
#define IDC_SET_LR2_2                   1319
#define IDC_SERV_FIRST_2                1320
#define IDC_RESET_VOLRAGE_1             1321
#define IDC_RESET_VOLRAGE_2             1322
#define IDC_RESET_TUBE_2                1323
#define IDC_RESET_TUBE_1                1324
#define IDC_RESET_TUBE_2_1              1325
#define IDC_RESET_TUBE_2_2              1326
#define IDC_CHECK_5MINUTES              1327
#define IDC_CHECK_DONE                  1328
#define IDC_CR_ORIGIN_1_1               1329
#define IDC_CHANGE_BATTERY2             1330
#define IDC_CHANGE_PUMP1_1              1330
#define IDC_CHANGE_PUMP2_1              1331
#define IDC_CHK_PARAM                   1332
#define IDC_SETIP_1                     1333
#define IDC_SETIP_2                     1334
#define IDC_CHECK_SETIP_DONE            1335
#define IDC_CHECK_SEPARATE              1336
#define IDC_RADIO1                      1337
#define IDC_RADIO_LCD_BOARD             1337
#define IDC_RADIO3                      1338
#define IDC_RADIO_HALT2                 1338
#define IDC_BACKUP_MSG1                 1346
#define IDC_IP_CLEAR_MSG1               1347
#define IDC_BARCODE_EDIT1               1349
#define IDC_BARCODE_EDIT2               1350
#define IDC_BARCODE_MSG1                1351
#define IDC_BARCODE_MSG2                1352
#define IDC_BARCODE_MSG3                1353
#define IDC__INIT_INK_STATE             1354
#define IDC_COMBO1                      1355
#define IDC_COMBO2                      1356
#define IDC_COMBO3                      1357
#define IDC_COMBO4                      1358
#define IDC_INIT_INK_K                  1359
#define IDC_INIT_INK_YCM                1360
#define IDC_INIT_INK_W1                 1361
#define IDC_INIT_INK_W2W4               1362
#define IDC_VRATING1                    1373
#define IDC_VRATING2                    1374
#define IDC_VRATING3                    1375
#define IDC_BTN_OPEN_VRATING            1376
#define IDC_CHECK_VRATING_DONE          1377
#define IDC_RTC_SET_AND_RESET_MSG2      1378
#define IDC_EEPROM_RESTORE_MSG1         1379
#define IDC_RTC_AND_RESET1              1381
#define IDC_BUTTON1                     1382
#define IDC_RADIO_HALT1                 1385
#define IDC_WHITE_HALT_MSG1             1386
#define IDC_WHITE_HALT_MSG2             1387
#define IDC_PLATEN_FEEDING_MSG1         1388
#define IDC_PLATEN_FEEDING_MSG2         1389
#define IDC_PLATEN_FEEDING_MSG3         1390
#define IDC_CHECK_PLATEN_FEEDING_DONE   1391
#define IDC_RTC_AND_RESET_BATTERY1      1392
#define IDC_BARCODE_MSG4                1393
#define IDC_BARCODE_MSG5                1394
#define IDC_RADIO_REGION_JPN            1395
#define IDC_RADIO_REGION_US             1396
#define IDC_RADIO_REGION_EUR            1397
#define IDC_RADIO_REGION_AUS            1398
#define IDC_RADIO_REGION_CHN            1399
#define IDC_BTN_CHECK                   1400
#define IDC_DATEPICKER                  1401
#define IDC_EDIT_WHITE                  1402
#define IDC_COLORHEAD                   1403
#define IDC_WHITEHEAD                   1404
#define IDC_INSTALLDATE                 1405
#define IDC_RADIO_MODEL_PRO             1406
#define IDC_RADIO_MODEL_PROB            1407
#define IDC_RADIO_HUMID_FAN             1408
#define IDC_HUMIDFAN_MSG1               1409
#define IDC_UPG_PSEL1_1                 1410
#define IDS_UPG_PSEL1_1                 1411
#define IDC_UPD_FIRM_MSG1               1412
#define IDC_UPD_FIRM_MSG2               1413
#define IDC_BTN_OPEN_FIRMUPDATE         1414
#define IDC_CHECK_UPD_FIRM_DONE         1415
#define IDS_UPD_FIRM_MSG1_1             1416
#define IDS_UPD_FIRM_MSG2_1             1417
#define IDS_BTN_OPEN_GTFIRM1_1          1418
#define IDS_UPD_FIRM_MSG3_1             1419
#define IDS_UPD_FIRM_MSG1_2             1420
#define IDS_UPD_FIRM_MSG2_2             1421
#define IDS_BTN_OPEN_GTFIRM1_2          1422
#define IDS_UPD_FIRM_MSG3_2             1423
#define IDC_WAIT_ACTION_MSG1            1424
#define IDS_WAIT_ACTION_MSG1_1          1425
#define IDS_WAIT_ACTION_MSG2_1          1426
#define IDC_18CODE_MSG1                 1427
#define IDC_18CODE_MSG2                 1428
#define IDC_USE_FIXED_18CODE            1429
#define IDC_18CODE_EDIT1                1430
#define IDS_USE_FIXED_18CODE            1431
#define IDS_18CODE_MSG1_1               1432
#define IDS_18CODE_MSG2_1               1433
#define IDS_WAIT_ACTION_MSG3_1          1434
#define IDS_EER_FIRM_VER                1435
#define IDS_ERR_FIRM_VER                1435
#define ID_MENU_PROD_INITSET            32771
#define IDC_LOG_CHECK2_2                65535
#define IDC_LOGFILE                     65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1416
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
